POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer x

{
    "author": "Test Author",
    "url": "example.com",
    "title": "Some random test title",
    "year": 2012
}